---
services:

  redis:
    image: redis:latest
    container_name: htc-redis
    networks:
      - htc-network
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    # Redis otimizado para alta performance
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --stop-writes-on-bgsave-error no

  cassandra:
    image: cassandra:4.1
    container_name: htc-cassandra-db
    ports:
      - "9042:9042"
    networks:
      - htc-network
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra
      # Otimizações de performance críticas
      - CASSANDRA_CLUSTER_NAME=htc_cluster
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
      - JVM_OPTS=-Dcassandra.consistent.rangemovement=false -Dcassandra.skip_wait_for_gossip_to_settle=0
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra-init:/docker-entrypoint-initdb.d
      - ./cassandra-config/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-config/jvm.options:/etc/cassandra/jvm.options
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' | grep -q 'system'"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s
    # Recursos dedicados para Cassandra
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    # Configurações do kernel para otimização
    sysctls:
      - net.core.rmem_max=134217728
      - net.core.wmem_max=134217728
      - net.ipv4.tcp_rmem=4096 65536 134217728
      - net.ipv4.tcp_wmem=4096 65536 134217728
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 100000
        hard: 100000
      nproc: 32768

  ds-studio:
    image: datastax/dse-studio:latest
    container_name: htc-ds-studio
    environment:
      - DS_LICENSE=accept
    ports:
      - "9091:9091"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - htc-network

  node1:
    build: .
    container_name: node_1
    hostname: node1
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - htc-network
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: node1
      CLUSTER_NAME: node1
      SEED_PORT_1600_TCP_ADDR: node1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MANAGEMENT_HTTP_PORT: 8558
      HTC_SIMULATION_CONFIG_FILE: /app/hyperbolic-time-chamber/simulations/input/cenario_sao_paulo_2500/simulation.json
      HTC_MOBILITY_CITY_MAP_FILE: /app/hyperbolic-time-chamber/simulations/input/cenario_sao_paulo_2500/data/city_map.json
      # Configurações JVM otimizadas
      JAVA_OPTS: >
        -Xms2g -Xmx4g 
        -XX:+UseG1GC 
        -XX:+UseStringDeduplication
        -XX:MaxGCPauseMillis=100
        -Dpekko.actor.default-dispatcher.fork-join-executor.parallelism-max=8
        -Dpekko.persistence.cassandra.journal.write-timeout=30s
        -Dpekko.persistence.cassandra.journal.read-timeout=15s
        -Dpekko.persistence.cassandra.snapshot.write-timeout=30s
        -Dpekko.persistence.cassandra.snapshot.read-timeout=15s
    volumes:
      - /home/dean/PhD/hyperbolic-time-chamber:/app/hyperbolic-time-chamber
    # Recursos dedicados para a aplicação
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: '3.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    # Aguardar mais tempo para inicialização
    restart: unless-stopped

volumes:
  redis_data:
  cassandra_data:

networks:
  htc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16