---
services:

  redis:
    image: redis:latest
    container_name: htc-redis
    networks:
      - htc-network
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  node1:
    build: .
    container_name: node_1
    hostname: node1
    networks:
      - htc-network
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: node1
      CLUSTER_NAME: node1
      SEED_PORT_1600_TCP_ADDR: node1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MANAGEMENT_HTTP_PORT: 8558
      # 🆕 Usar configuração ULTRA-OTIMIZADA
      JAVA_OPTS: "-Dconfig.resource=application-ultra.conf"
      # Configuração para CSV reports
      HTC_REPORT_STRATEGY: csv
      HTC_SIMULATION_CONFIG_FILE: /app/hyperbolic-time-chamber/simulations/input/cenario_1M_viagens/simulation.json
      HTC_MOBILITY_CITY_MAP_FILE: /app/hyperbolic-time-chamber/simulations/input/cenario_1M_viagens/data/city_map.json
    volumes:
      - /home/dean/hyperbolic-time-chamber:/app/hyperbolic-time-chamber


volumes:
  redis_data:
  htc_persistence:  # Para armazenar snapshots/journal localmente

networks:
  htc-network:
    driver: bridge