package org.interscity.htc
package model.mobility.entity.state.enumeration

enum EventTypeEnum:
  case Arrival,
    Departure,
    Stop,
    Start,
    Pass,
    Enter,
    Exit,
    Change,
    Wait,
    Finish,
    RequestRoute,
    ForwardRoute,
    ReceiveRoute,
    ReceiveSignalState,
    EnterLink,
    LeaveLink,
    EnterNode,
    LeaveNode,
    ReceiveEnterLinkInfo,
    ReceiveLeaveLinkInfo,
    ReceiveEnterNodeInfo,
    ReceiveLeaveNodeInfo,
    TrafficSignalChangeStatus,
    RequestSignalState,
    // Event-driven events (new)
    RequestEnterLink,
    EnterLinkConfirm,
    ArriveAtNode,
    PhaseChange,
    RequestSignalPrediction,
    SignalPrediction,
    RegisterBusStop,
    RegisterSubwayStation
