include "application"

pekko {
  discovery.method = kubernetes-api

  discovery.kubernetes-api {
    pod-label-selector = "app=htc-node"
  }

  cluster.bootstrap.contact-point-discovery {
    discovery-method = kubernetes-api
    service-name = "htc-simulator"
  }

  management {
    http {
      bind-hostname = "0.0.0.0"
      hostname = ${?POD_IP}
      hostname = ${?CLUSTER_IP}
    }

    cluster.bootstrap {
      new-cluster-enabled = off
      contact-point-discovery.required-contact-point-nr = 1
    }

    cluster.bootstrap.contact-point-discovery {
      discovery-method = kubernetes-api
      service-name = "htc-simulator"
    }
  }
}

clustering.ip = ${?POD_IP}
clustering.ip = ${?CLUSTER_IP}